-- Full Dermatology Database Schema
-- Includes Funnel 1 (Skin Flows) and Funnel 2 (Medical Chat, EMR)

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- ==========================================
-- 1. User Management & RBAC
-- ==========================================
create table if not exists public.staff_users (
    id uuid default uuid_generate_v4() primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    role text not null check (role in ('admin', 'doctor', 'staff')),
    name text,
    created_at timestamptz default now(),
    unique(user_id)
);

create table if not exists public.audit_logs (
    id uuid default uuid_generate_v4() primary key,
    user_id uuid references auth.users(id),
    action text not null,
    details jsonb,
    created_at timestamptz default now()
);

-- ==========================================
-- 2. Funnel 1: Skin Flows (Dermatology Tests)
-- ==========================================
create table if not exists public.skin_flows (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references auth.users(id) on delete set null, -- Nullable for anonymous users
  flow_type text not null, -- 'skin_mbti', 'skin_age', 'uv_score', 'cleansing_lab', 'trouble_map'
  answers_json jsonb, -- Raw answers from the user
  result_json jsonb, -- Final result + CTA data
  created_at timestamptz default now()
);

-- ==========================================
-- 3. Funnel 2: Chat System (Persistence)
-- ==========================================
create table if not exists public.chat_sessions (
    id uuid default uuid_generate_v4() primary key,
    user_id uuid references auth.users(id) on delete set null,
    topic text not null, -- e.g., 'skin_mbti', 'consultation'
    title text,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create table if not exists public.chat_messages (
    id uuid default uuid_generate_v4() primary key,
    session_id uuid references public.chat_sessions(id) on delete cascade not null,
    role text not null check (role in ('user', 'assistant', 'system')),
    content text not null,
    created_at timestamptz default now()
);

-- ==========================================
-- 4. Patient Care (EMR)
-- ==========================================
create table if not exists public.patients (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete set null unique, -- Link to auth user
    created_at timestamptz default now(),
    name text not null,
    birth_date date,
    gender text,
    phone text,
    email text,
    address text,
    medical_history text,
    status text check (status in ('pending', 'active', 'archived')) default 'active'
);

create table if not exists public.visits (
    id uuid default uuid_generate_v4() primary key,
    patient_id bigint references public.patients(id) on delete cascade not null,
    visit_date timestamptz default now(),
    visit_type text not null, -- e.g., 'consultation', 'treatment', 'checkup'
    status text check (status in ('scheduled', 'in_progress', 'completed', 'cancelled')) default 'scheduled',
    chief_complaint text,
    cancellation_reason text, -- Added as requested
    created_at timestamptz default now()
);

create table if not exists public.clinical_notes (
    id uuid default uuid_generate_v4() primary key,
    visit_id uuid references public.visits(id) on delete cascade not null,
    author_id uuid references auth.users(id),
    content text not null,
    note_type text default 'general', -- 'soap', 'procedure', etc.
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create table if not exists public.clinical_images (
    id uuid default uuid_generate_v4() primary key,
    visit_id uuid references public.visits(id) on delete cascade,
    patient_id bigint references public.patients(id) on delete cascade,
    image_url text not null,
    analysis_result jsonb,
    created_at timestamptz default now()
);

create table if not exists public.treatment_plans (
    id uuid default uuid_generate_v4() primary key,
    patient_id bigint references public.patients(id) on delete cascade not null,
    title text not null,
    description text,
    estimated_cost numeric,
    status text check (status in ('proposed', 'accepted', 'completed', 'declined')) default 'proposed',
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

-- ==========================================
-- 5. Analysis & Intake
-- ==========================================
create table if not exists public.intake_summaries (
    id uuid default uuid_generate_v4() primary key,
    user_id uuid references auth.users(id) on delete set null,
    flow_type text not null,
    summary text not null,
    raw_data jsonb,
    created_at timestamptz default now()
);

-- ==========================================
-- 6. RLS Policies
-- ==========================================
alter table public.staff_users enable row level security;
alter table public.audit_logs enable row level security;
alter table public.skin_flows enable row level security;
alter table public.chat_sessions enable row level security;
alter table public.chat_messages enable row level security;
alter table public.patients enable row level security;
alter table public.visits enable row level security;
alter table public.clinical_notes enable row level security;
alter table public.clinical_images enable row level security;
alter table public.treatment_plans enable row level security;
alter table public.intake_summaries enable row level security;

-- Staff Users
create policy "Allow read access for all users" on public.staff_users for select using (true);
create policy "Allow write access for admins" on public.staff_users for insert with check (
    exists (select 1 from public.staff_users where user_id = auth.uid() and role = 'admin')
);

-- Skin Flows
create policy "Users can view own skin flows" on public.skin_flows for select using (auth.uid() = user_id);
create policy "Users can update own skin flows" on public.skin_flows for update using (auth.uid() = user_id);
-- Allow public insert for anonymous users (handled by API usually, but if client-side needed)
create policy "Anyone can insert skin flows" on public.skin_flows for insert with check (true);

-- Chat Sessions & Messages
create policy "Users can view own sessions" on public.chat_sessions for select using (auth.uid() = user_id);
create policy "Users can insert own sessions" on public.chat_sessions for insert with check (auth.uid() = user_id);
create policy "Users can view own messages" on public.chat_messages for select using (
    exists (select 1 from public.chat_sessions where id = chat_messages.session_id and user_id = auth.uid())
);
create policy "Users can insert own messages" on public.chat_messages for insert with check (
    exists (select 1 from public.chat_sessions where id = chat_messages.session_id and user_id = auth.uid())
);

-- Patients
create policy "Users can view own patient record" on public.patients for select using (auth.uid() = user_id);
create policy "Users can update own patient record" on public.patients for update using (auth.uid() = user_id);
create policy "Users can insert own patient record" on public.patients for insert with check (auth.uid() = user_id);
create policy "Staff can view patients" on public.patients for select using (auth.role() = 'authenticated'); -- Simplified for MVP
create policy "Staff can edit patients" on public.patients for all using (auth.role() = 'authenticated'); -- Simplified for MVP

-- Visits
create policy "Users can view own visits" on public.visits for select using (
    exists (select 1 from public.patients where id = visits.patient_id and user_id = auth.uid())
);
create policy "Allow public insert access for visits" on public.visits for insert with check (true); -- For booking
create policy "Staff can view all visits" on public.visits for select using (auth.role() = 'authenticated');
create policy "Staff can update visits" on public.visits for update using (auth.role() = 'authenticated');

-- Clinical Data (Notes, Images, Plans)
-- Staff access
create policy "Staff can manage clinical notes" on public.clinical_notes for all using (auth.role() = 'authenticated');
create policy "Staff can manage clinical images" on public.clinical_images for all using (auth.role() = 'authenticated');
create policy "Staff can manage treatment plans" on public.treatment_plans for all using (auth.role() = 'authenticated');

-- Patient access (View only)
create policy "Patients can view own treatment plans" on public.treatment_plans for select using (
    exists (select 1 from public.patients where id = treatment_plans.patient_id and user_id = auth.uid())
);

-- ==========================================
-- 7. Initial Data
-- ==========================================
-- Note: You must manually insert a staff user into 'public.staff_users' 
-- using a valid 'id' from 'auth.users' after you have signed up.
-- Example:
-- insert into public.staff_users (user_id, role, name)
-- values ('YOUR-VALID-USER-ID-FROM-AUTH-USERS', 'admin', 'System Admin');
